version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    # volumes:
    #   - "./mongodb:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
  mongo-express:
    # build:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 3000:3000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      # ME_CONFIG_MONGODB_SERVER: localhost
      ME_CONFIG_MONGODB_SERVER: mongodb
      # ME_CONFIG_MONGODB_URL: "mongodb://root:123@kubernetes.docker.internal:27017"
    # depends_on:
    #   - mongodb
    links:
      - mongodb
    
# version: "3"
# services:
#  backend-app-001:
#     build: .
#     ports:
#       - "3000:3000"
#     links:
#       - mongodb-001
#  mongodb-001:
#     image: mongo:6.0-focal
#     ports:
#       - "27017:27017"
#     volumes:
#       - "./data:/data/db"